services:
  - type: web
    name: preview-sync
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - fromGroup: API
      
previews:
  generation: automatic